language: node_js
node_js:
  - 14.16.0

branches:
  only:
    - master

cache:
 directories:
   - node_modules

script: "npm run build"

before_install:
     - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in ./.env.production.enc -out ./.env.production -d

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - pozafly@kakao.com