language: node_js

# nodeJS 버전
node_js:
- 14.16.0

# Git Commit 수신 허용 목록 master 브랜치만.
branches:
  only:
  - master

# Travis CI 에서 node_modules를 캐싱한다.
# 빌드 프로세스 속도를 높여줌.
cache:
  directories:
  - node_modules

# Travis 서버에서 빌드 명령어
script: npm run build

# .env.production 파일 인코딩했던 것을 디코딩해서 만들어줌.
before_install:
- openssl aes-256-cbc -K $encrypted_538818e76846_key -iv $encrypted_538818e76846_iv
  -in .env.production.enc -out .env.production -d

# AWS CloudFront 캐싱을 위해 설치.
before_deploy:
  - npm install -g travis-ci-cloudfront-invalidation

# build후 배포 대상
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: tripllo.tech
  skip_cleanup: true
  acl: public_read
  region: ap-northeast-2
  wait-until-deploy: true
  local_dir: dist

# 배포 완료 후 AWS CloudFront의 캐시를 무효화.
after_deploy:
  - aws configure set preview.cloudfront true
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_KEY -c $AWS_CLOUDFRONT_DIST_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master'

# 빌드 후 알림
notifications:
  email:
    recipients:
    - pozafly@kakao.com
