language: node_js

node_js:
- 14.16.0

branches:
  only:
  - master

cache:
  directories:
  - node_modules

script: npm run build

before_install:
- openssl aes-256-cbc -K $encrypted_538818e76846_key -iv $encrypted_538818e76846_iv
  -in .env.production.enc -out .env.production -d

before_deploy:
  - pip install --user awscli

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: tripllo.tech
  skip_cleanup: true
  acl: public_read
  region: ap-northeast-2
  wait-until-deploy: true
  local_dir: dist

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

notifications:
  email:
    recipients:
    - pozafly@kakao.com
